# Generated by Django 5.1a1 on 2024-08-07 11:31

import django.core.validators
import django.db.models.deletion
import uuid
import warehouse.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DrugFormChoice",
            fields=[
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("extra_info", models.TextField(blank=True, max_length=250)),
                ("is_deleted", models.BooleanField(blank=True, default=False)),
                ("deleted_at", models.DateField(blank=True, editable=False, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("value", models.CharField(max_length=15, unique=True)),
                ("description", models.CharField(max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        auto_created=warehouse.models.user.User,
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Drug form choice",
                "verbose_name_plural": "Drug form choices",
                "ordering": ["value"],
            },
        ),
        migrations.CreateModel(
            name="ApprovedDrug",
            fields=[
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("extra_info", models.TextField(blank=True, max_length=250)),
                ("is_deleted", models.BooleanField(blank=True, default=False)),
                ("deleted_at", models.DateField(blank=True, editable=False, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("is_approved", models.BooleanField(default=True)),
                ("components", models.TextField(blank=True, max_length=300, null=True)),
                ("main_component_dosage", models.CharField(max_length=20)),
                (
                    "main_component_unit",
                    models.CharField(
                        choices=[
                            ("mg", "MG"),
                            ("g", "G"),
                            ("ml", "ML"),
                            ("pcs", "PCS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.FileField(upload_to="uploads/")),
                ("usage_time", models.PositiveIntegerField()),
                (
                    "usage_time_unit",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        auto_created=warehouse.models.user.User,
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="warehouse.drugformchoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approved drug",
                "verbose_name_plural": "Approved drugs",
                "ordering": ["created_at"],
                "unique_together": {("name", "main_component_dosage", "form")},
            },
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("extra_info", models.TextField(blank=True, max_length=250)),
                ("is_deleted", models.BooleanField(blank=True, default=False)),
                ("deleted_at", models.DateField(blank=True, editable=False, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rack",
                    models.CharField(
                        help_text="Enter a two digit rack number (01, 02, 11,...)",
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_rack",
                                message="Enter a two digit rack number (01, 02, 11,...)",
                                regex="^\\d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "box",
                    models.CharField(
                        choices=[
                            ("NEW", "NEW"),
                            ("1F-A", "1F-A"),
                            ("1F-B", "1F-B"),
                            ("1F-C", "1F-C"),
                            ("1F-D", "1F-D"),
                            ("2F-A", "2F-A"),
                            ("2F-B", "2F-B"),
                            ("2F-C", "2F-C"),
                            ("2F-D", "2F-D"),
                            ("3F-A", "3F-A"),
                            ("3F-B", "3F-B"),
                            ("3F-C", "3F-C"),
                            ("3F-D", "3F-D"),
                            ("4F-A", "4F-A"),
                            ("4F-B", "4F-B"),
                            ("4F-C", "4F-C"),
                            ("4F-D", "4F-D"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        auto_created=warehouse.models.user.User,
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="basic_informations_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage",
                "verbose_name_plural": "Storages",
                "ordering": ["rack", "box"],
                "unique_together": {("rack", "box")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("extra_info", models.TextField(blank=True, max_length=250)),
                ("is_deleted", models.BooleanField(blank=True, default=False)),
                ("deleted_at", models.DateField(blank=True, editable=False, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("serial_number", models.CharField(max_length=20)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "quantity_unit",
                    models.CharField(
                        choices=[
                            ("mg", "MG"),
                            ("g", "G"),
                            ("ml", "ML"),
                            ("pcs", "PCS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("best_before_date", models.DateField()),
                (
                    "is_opened",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("opened_date", models.DateField(blank=True, null=True)),
                (
                    "approved_drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="warehouse.approveddrug",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        auto_created=warehouse.models.user.User,
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="warehouse.storage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["created_at"],
                "unique_together": {("approved_drug", "serial_number")},
            },
        ),
    ]
