# Generated by Django 5.1a1 on 2024-08-07 11:31

from django.db import migrations
from django.db.models import Q
import uuid


def create_user_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    groups_permissions = {
        "superuser": Permission.objects.all(),
        "senior_user": Permission.objects.filter(
            Q(codename__istartswith='add') |
            Q(codename__istartswith='change') |
            Q(codename__istartswith='view') |
            Q(codename__istartswith='delete')
        ),
        "standard_user": Permission.objects.filter(
            Q(codename__istartswith='add') |
            Q(codename__istartswith='change') |
            Q(codename__istartswith='view')
        ),
        "view_only": Permission.objects.filter(Q(codename__istartswith='view')),
    }

    for group_name, permissions in groups_permissions.items():
        group, created = Group.objects.get_or_create(name=group_name)
        group.permissions.set(permissions)



def add_drug_form_choices(apps, schema_editor):
    DrugFormChoice = apps.get_model('warehouse', 'DrugFormChoice')

    choices = [
        ("ampoule", "Ampoule"),
        ("capsules", "Capsules"),
        ("cream", "Cream"),
        ("drink", "Drink"),
        ("drops", "Drops"),
        ("emulsion", "Emulsion"),
        ("gas", "Gas"),
        ("gelhydrogel", "Gel/hydrogel"),
        ("forinh", "For inhalations"),
        ("injections", "Injections"),
        ("lotion", "Lotion"),
        ("pastille", "Pastille"),
        ("paste", "Paste"),
        ("patch", "Patch"),
        ("pills", "Pills"),
        ("powder", "Powder"),
        ("spray", "Spray"),
        ("syrup", "Syrup"),
        ("thinfilms", "Thin films"),
        ("otherderm", "Other/dermal"),
        ("otherext", "Other/external use"),
        ("otherli", "Other/liquid"),
        ("otheror", "Other/oral"),
    ]

    for value, description in choices:
        DrugFormChoice.objects.create(
            id=uuid.uuid4(),
            value=value,
            description=description
        )


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_user_groups),
    migrations.RunPython(add_drug_form_choices)]
