# Generated by Django 5.1a1 on 2024-08-07 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_approveddrug_is_controlled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantity",
            new_name="packaging_quantity",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="quantity_unit",
            new_name="packaging_quantity_unit",
        ),
        migrations.AlterField(
            model_name="approveddrug",
            name="main_component_dosage",
            field=models.IntegerField(
                help_text="Enter a positive value",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="approveddrug",
            name="usage_time",
            field=models.PositiveIntegerField(help_text="Enter a positive value"),
        ),
    ]
