# Generated by Django 5.1a1 on 2024-08-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0006_approveddrug_str_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approveddrug",
            name="str_prefix",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
    ]
