# Generated by Django 5.1a1 on 2024-08-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0008_alter_approveddrug_str_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approveddrug",
            name="str_prefix",
            field=models.CharField(default="", max_length=30),
        ),
    ]
